#!/bin/bash

echo "🚀 Deploying VibeCoding Railway Template"
echo "======================================="

# Check if we're in the right directory
if [ ! -f "Dockerfile" ]; then
    echo "❌ Error: Dockerfile not found. Make sure you're in the railway-template directory."
    exit 1
fi

echo "📋 Template files:"
echo "✅ Dockerfile"
echo "✅ railway.toml"
echo "✅ start-dev-environment.sh"
echo "✅ claude-context-manager.py"
echo "✅ README.md"
echo ""

echo "📝 Next steps to deploy this template to Railway:"
echo ""
echo "1. 🔗 Create a new GitHub repository for this template:"
echo "   - Repository name: vibecoding-railway-template"
echo "   - Make it public (Railway templates need to be public)"
echo "   - Push all these files to the repository"
echo ""
echo "2. 🚀 Deploy to Railway:"
echo "   - Go to https://railway.app"
echo "   - Create new project from GitHub"
echo "   - Select your vibecoding-railway-template repository"
echo "   - Railway will automatically detect Dockerfile and deploy"
echo ""
echo "3. 📋 Configure as Template:"
echo "   - In Railway project settings, mark as 'Template'"
echo "   - Set template ID: vibecoding-react-vite-supabase"
echo "   - Add description and tags"
echo ""
echo "4. ✅ Test the template:"
echo "   - Try deploying from template"
echo "   - Verify all services start correctly"
echo "   - Test health check endpoint"
echo ""
echo "5. 🔧 Update VibeCoding project-creator:"
echo "   - Set RAILWAY_TEMPLATE_ID=vibecoding-react-vite-supabase"
echo "   - Test project creation end-to-end"
echo ""
echo "🎯 Template will provide:"
echo "   - Pre-built React+Vite+Supabase environment"
echo "   - Claude MCP server on port 8080"
echo "   - Vite dev server on port 3000"
echo "   - Auto-clone GitHub repositories"
echo "   - Health monitoring and auto-recovery"
echo ""
echo "Ready to deploy! 🚀" 